### ISSUE TITLE
build_posterior got unexpected keyword argument sampling_parameters when running SNPE_C

### ISSUE THREAD

**Issue by JunmiHu** [bgroenks96/SimulationBasedInference.jl#6]
## Description
Hi, this issue is related to issue #5. However, this time the issue is with regards to the SNPE_C algorithm. When calling solve with SNPE_C, it encounters an error in the build_posterior() funciton. This seems to be because direct_parameters is not a keyword supported by build_posterior (I believe "direct_sampling_parameters") is the correct parameter name. 

Moreover, as of the current sbi release (v0.22.0, released Dec 4, 2023), sample_with = "direct" is not a supported method, although it is supported on the current dev-version.  I'm not sure if there is a quick workaround for this problem, or if it is more constructive to just wait for the next release of sbi. 

### To reproduce
```
using PythonCall
using SimulationBasedInference
using SimulationBasedInference.PySBI
using OrdinaryDiffEq
import Random

### Define the ODE inference problem
const rng = Random.MersenneTwister(1234);
ode_func(u,p,t) = -p[1]*u;
α_true = 0.2
ode_p = [α_true];
tspan = (0.0,10.0);
odeprob = ODEProblem(ode_func, [1.0], tspan, ode_p)

dt = 0.2
tsave = tspan[begin]+dt:dt:tspan[end];
n_obs = length(tsave);
observable = ODEObservable(:y, odeprob, tsave, samplerate=0.01);
forward_prob = SimulatorForwardProblem(odeprob, observable)

ode_solver = Tsit5()
forward_sol = solve(forward_prob, ode_solver);
true_obs = get_observable(forward_sol, :y)
noise_scale = 0.05
noisy_obs = true_obs .+ noise_scale*randn(rng, n_obs);

model_prior = prior(α=Beta(2,2));
noise_scale_prior = prior(σ=Exponential(0.1));

lik = IsotropicGaussianLikelihood(observable, noisy_obs, noise_scale_prior);
inference_prob = SimulatorInferenceProblem(forward_prob, ode_solver, model_prior, lik);

### Run inference
snpe_sol = solve(inference_prob, PySBI.SNPE_C(), rng=rng, num_rounds = 3)
```

### Stack trace
ERROR: Python: TypeError: PosteriorEstimator.build_posterior() got an unexpected keyword argument 'direct_parameters'
Python stacktrace: none
Stacktrace:
  [1] pythrow()
    @ PythonCall.Core ~/.julia/packages/PythonCall/sQSpa/src/Core/err.jl:92
  [2] errcheck
    @ ~/.julia/packages/PythonCall/sQSpa/src/Core/err.jl:10 [inlined]
  [3] pycallargs
    @ ~/.julia/packages/PythonCall/sQSpa/src/Core/builtins.jl:222 [inlined]
  [4] pycall(f::Py, args::Py; kwargs::@Kwargs{sample_with::String, direct_parameters::Dict{String, Integer}})
    @ PythonCall.Core ~/.julia/packages/PythonCall/sQSpa/src/Core/builtins.jl:237
  [5] pycall
    @ ~/.julia/packages/PythonCall/sQSpa/src/Core/builtins.jl:233 [inlined]
  [6] #_#11
    @ ~/.julia/packages/PythonCall/sQSpa/src/Core/Py.jl:357 [inlined]
  [7] _build_posterior(sampling::SimulationBasedInference.PySBI.DirectSampling, inference::Py, estimator::Py)
    @ SimulationBasedInference.PySBI ~/.julia/packages/SimulationBasedInference/ghyok/ext/pysbi/pysne.jl:178
  [8] step!(solver::SimulationBasedInference.PySBI.PySBISolver{PySNE, SimulationBasedInference.PySBI.DirectSampling})
    @ SimulationBasedInference.PySBI ~/.julia/packages/SimulationBasedInference/ghyok/ext/pysbi/pysne.jl:153
  [9] solve!(solver::SimulationBasedInference.PySBI.PySBISolver{PySNE, SimulationBasedInference.PySBI.DirectSampling})
    @ SimulationBasedInference.PySBI ~/.julia/packages/SimulationBasedInference/ghyok/ext/pysbi/pysne.jl:161
 [10] #solve#1
    @ ~/.julia/packages/CommonSolve/JfpfI/src/CommonSolve.jl:23 [inlined]
 [11] top-level scope
    @ ~/SBITesting.jl/example/linearode/snle_please.jl:34

**Comment by bgroenks96** [comment]
Sorry, that was a stupid mistake on my part. It was late and I didn't test SNPE. Fixed in ~~7053f3d9~~ 7ff5bc7e0a. Let me know if it works on your end and then we can close the issue.

We can update the default sampling algorithm choice when the next version of sbi is released.

Thanks for your patience.

**Comment by bgroenks96** [comment]
I had to push one additional commit to re-add the `method` property to `MCMCSampling`. So 7ff5bc7e0a is the latest commit that should work for both SNPE and SNLE.

**Comment by JunmiHu** [comment]
Great! I am not sure which commit caused the issue, but when running the same code with SNLE_A now (for num_simulations = 1000), it samples 10100 at each round. Running at 100 simulations causes to sample 1100, so it seems like there is some weird unintended multiplication that is happening. 

I believe the intended implementation should be 200 MCMC burn-in samples + num_samples. 

I've included the changed code below.
```
### Run inference
snpe_sol = solve(inference_prob, PySBI.SNPE_C(), rng=rng, num_rounds = 3)
```

### Example output
```
[ Info: Starting iteration 1/3
[ Info: Running simulations
Running 1000 simulations.: 100%|████████████████████████████████████████████████████████████████| 1000/1000 [00:08<00:00, 115.32it/s]
[ Info: Training estimator
[ Info: Building posteriorEpochs trained: 399
[ Info: Starting iteration 2/3
[ Info: Running simulations
Tuning bracket width...: 100%|██████████████████████████████████████████████████████████████████████| 50/50 [00:00<00:00, 121.99it/s]
Generating samples:   4%|███▏                                                                    | 450/10100 [00:22<07:45, 20.75it/s]
```

**Comment by bgroenks96** [comment]
I also noticed this, but it doesn't have anything to do with SBI.jl. It also happens if you run the python example code.

As far as I can tell, it has to do with however the thinning parameter (i.e. `thin`) is set by default. It probably sets it to 10 and thus you end up with 10 x 1000 samples + 100 warmup samples which must be the default in the current published version of `sbi` for the `slice_np` sampler.

You can fix this by specifying the `mcmc_parameters` yourself with `sampling = MCMCSampling(num_chains=1, thin=1)`.

Might also be worth raising an issue on `sbi` since this behavior is quite surprising and not transparent at all.
